# Generated by Django 3.2.6 on 2021-09-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='strains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strainName', models.CharField(max_length=255)),
                ('strainType', models.CharField(max_length=255)),
                ('strainRating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('strainEffefts', models.CharField(blank=True, max_length=255, null=True)),
                ('strainFlavor', models.CharField(blank=True, max_length=255, null=True)),
                ('strainDescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'strain',
                'db_table': 'strain',
            },
        ),
    ]
